export interface ApartamentsModel {
    id: string,
    imagePath: string,
    name: string,
    city: string,
    street: string,
    rentalFee: number,
    apartmentSize: number,
    rooms: number,
    description: string,
    floor: string,
    elevator: 'Yes' | 'No',
    parkingSpace: 'Yes' | 'No',
    available: 'Yes' | 'No',
}