import { Injectable, signal } from '@angular/core';
import { ApartamentsModel } from './apartaments.model';

@Injectable({
  providedIn: 'root',
})
export class ApartamentsStorage {
  public Apartaments = signal<ApartamentsModel[]>([
    {
      id: 'a1',
      imagePath: '/assets/images/apartaments/apartament1.jpg',
      name: 'ModernVista Centrum',
      city: 'Brodnica',
      street: 'Mostowa 44',
      rentalFee: 1800,
      apartmentSize: 45,
      rooms: 2,
      description: 'Modern apartment located in the city center.',
      fullDescription: 'A modern and fully equipped apartment located in the very heart of Brodnica. Perfect for people who value proximity to city attractions, comfort, and modern design.',
      floor: '1st',
      elevator: 'Yes',
      parkingSpace: 'No',
      available: 'Yes',
      details: {
        flat: {
          kitchenType: 'Open kitchen',
          bathroomWithToilet: 'Yes',
          balcony: 'No',
          terrace: 'No',
          market: 'Primary',
        },
        buidling: {
          buildingType: 'Apartment building',
          buildingMaterial: 'Brick',
          dateBuilding: '2018',
        },
        advertisement: {
          addedDate: '01-01-2025',
          lastUpdate: '10-01-2025',
          idAdvertisement: 'ADV-a1',
          views: 245,
        },
      },
    },
    {
      id: 'a2',
      imagePath: '/assets/images/apartaments/apartament2.jpg',
      name: 'ModernVista Riverside',
      city: 'Brodnica',
      street: 'Nad Drwęcą 1',
      rentalFee: 2100,
      apartmentSize: 60,
      rooms: 3,
      description: 'Spacious apartment near the river with a calm atmosphere.',
      fullDescription: 'Spacious apartment located near the river, offering peace and beautiful surroundings. Ideal for families or people seeking relaxation close to nature.',
      floor: '3rd',
      elevator: 'Yes',
      parkingSpace: 'Yes',
      available: 'Yes',
      details: {
        flat: {
          kitchenType: 'Separate kitchen',
          bathroomWithToilet: 'Yes',
          balcony: 'Yes',
          terrace: 'No',
          market: 'Primary',
        },
        buidling: {
          buildingType: 'Residential building',
          buildingMaterial: 'Concrete',
          dateBuilding: '2016',
        },
        advertisement: {
          addedDate: '03-01-2025',
          lastUpdate: '12-01-2025',
          idAdvertisement: 'ADV-a2',
          views: 312,
        },
      },
    },
    {
      id: 'a3',
      imagePath: '/assets/images/apartaments/apartament3.jpg',
      name: 'ModernVista Park',
      city: 'Brodnica',
      street: 'Parkowa 12',
      rentalFee: 1500,
      apartmentSize: 40,
      rooms: 2,
      description: 'Cozy apartment located next to a green park.',
      fullDescription: 'A cozy and functional apartment located next to a green park. Perfect for people who appreciate calm surroundings and daily contact with nature.',
      floor: '1st',
      elevator: 'Yes',
      parkingSpace: 'No',
      available: 'Yes',
      details: {
        flat: {
          kitchenType: 'Open kitchen',
          bathroomWithToilet: 'Yes',
          balcony: 'Yes',
          terrace: 'No',
          market: 'Secondary',
        },
        buidling: {
          buildingType: 'Low-rise building',
          buildingMaterial: 'Brick',
          dateBuilding: '2012',
        },
        advertisement: {
          addedDate: '05-01-2025',
          lastUpdate: '14-01-2025',
          idAdvertisement: 'ADV-a3',
          views: 198,
        },
      },
    },
    {
      id: 'a4',
      imagePath: '/assets/images/apartaments/apartament4.jpg',
      name: 'ModernVista Lake View',
      city: 'Brodnica',
      street: 'Jeziorna 2',
      rentalFee: 2300,
      apartmentSize: 72,
      rooms: 3,
      description: 'Premium apartment with a beautiful lake view.',
      fullDescription: 'Premium apartment offering a stunning lake view and high-standard interior finish. Designed for tenants seeking luxury and comfort.',
      floor: '2nd',
      elevator: 'Yes',
      parkingSpace: 'Yes',
      available: 'No',
      details: {
        flat: {
          kitchenType: 'Open kitchen',
          bathroomWithToilet: 'Yes',
          balcony: 'Yes',
          terrace: 'Yes',
          market: 'Primary',
        },
        buidling: {
          buildingType: 'Luxury apartment building',
          buildingMaterial: 'Concrete',
          dateBuilding: '2020',
        },
        advertisement: {
          addedDate: '07-01-2025',
          lastUpdate: '15-01-2025',
          idAdvertisement: 'ADV-a4',
          views: 421,
        },
      },
    },
    {
      id: 'a5',
      imagePath: '/assets/images/apartaments/apartament5.jpg',
      name: 'ModernVista Old Town',
      city: 'Brodnica',
      street: 'Duży Rynek 53a',
      rentalFee: 1700,
      apartmentSize: 48,
      rooms: 2,
      description: 'Stylish apartment in the historic Old Town.',
      fullDescription: 'Stylish apartment located in the heart of Brodnica’s Old Town. Ideal for people who enjoy historic surroundings combined with modern comfort.',
      floor: '3rd',
      elevator: 'Yes',
      parkingSpace: 'No',
      available: 'Yes',
      details: {
        flat: {
          kitchenType: 'Open kitchen',
          bathroomWithToilet: 'Yes',
          balcony: 'No',
          terrace: 'No',
          market: 'Secondary',
        },
        buidling: {
          buildingType: 'Historic building',
          buildingMaterial: 'Brick',
          dateBuilding: '2005',
        },
        advertisement: {
          addedDate: '09-01-2025',
          lastUpdate: '18-01-2025',
          idAdvertisement: 'ADV-a5',
          views: 287,
        },
      },
    },
    {
      id: 'a6',
      imagePath: '/assets/images/apartaments/apartament6.jpg',
      name: 'ModernVista Business',
      city: 'Brodnica',
      street: 'Kamionka 22',
      rentalFee: 1900,
      apartmentSize: 55,
      rooms: 2,
      description: 'Perfect for business stays with a dedicated workspace.',
      fullDescription: 'Apartment designed for business travelers, offering a dedicated workspace and fast access to city infrastructure.',
      floor: '4th',
      elevator: 'Yes',
      parkingSpace: 'Yes',
      available: 'Yes',
      details: {
        flat: {
          kitchenType: 'Separate kitchen',
          bathroomWithToilet: 'Yes',
          balcony: 'Yes',
          terrace: 'No',
          market: 'Primary',
        },
        buidling: {
          buildingType: 'Modern apartment building',
          buildingMaterial: 'Concrete',
          dateBuilding: '2019',
        },
        advertisement: {
          addedDate: '10-01-2025',
          lastUpdate: '20-01-2025',
          idAdvertisement: 'ADV-a6',
          views: 334,
        },
      },
    },
    {
      id: 'a7',
      imagePath: '/assets/images/apartaments/apartament7.jpg',
      name: 'ModernVista Comfort',
      city: 'Brodnica',
      street: 'Wybickiego 55',
      rentalFee: 1600,
      apartmentSize: 42,
      rooms: 2,
      description: 'Comfortable apartment in a quiet residential area.',
      fullDescription: 'Comfortable apartment located in a peaceful residential area, ideal for long-term tenants seeking calm and privacy.',
      floor: '1st',
      elevator: 'Yes',
      parkingSpace: 'No',
      available: 'No',
      details: {
        flat: {
          kitchenType: 'Open kitchen',
          bathroomWithToilet: 'Yes',
          balcony: 'Yes',
          terrace: 'No',
          market: 'Secondary',
        },
        buidling: {
          buildingType: 'Residential building',
          buildingMaterial: 'Brick',
          dateBuilding: '2010',
        },
        advertisement: {
          addedDate: '11-01-2025',
          lastUpdate: '21-01-2025',
          idAdvertisement: 'ADV-a7',
          views: 198,
        },
      },
    },
    {
      id: 'a8',
      imagePath: '/assets/images/apartaments/apartament8.jpg',
      name: 'ModernVista Premium',
      city: 'Brodnica',
      street: 'Mazurska 3',
      rentalFee: 2400,
      apartmentSize: 78,
      rooms: 4,
      description: 'High-end apartment with premium interior finish.',
      fullDescription: 'High-end apartment finished with premium materials, offering spacious rooms and elegant design.',
      floor: '3rd',
      elevator: 'Yes',
      parkingSpace: 'Yes',
      available: 'Yes',
      details: {
        flat: {
          kitchenType: 'Open kitchen',
          bathroomWithToilet: 'Yes',
          balcony: 'Yes',
          terrace: 'Yes',
          market: 'Primary',
        },
        buidling: {
          buildingType: 'Luxury residence',
          buildingMaterial: 'Concrete',
          dateBuilding: '2021',
        },
        advertisement: {
          addedDate: '12-01-2025',
          lastUpdate: '22-01-2025',
          idAdvertisement: 'ADV-a8',
          views: 512,
        },
      },
    },
    {
      id: 'a9',
      imagePath: '/assets/images/apartaments/apartament9.jpg',
      name: 'ModernVista Green',
      city: 'Brodnica',
      street: 'Zielona 8',
      rentalFee: 1450,
      apartmentSize: 38,
      rooms: 1,
      description: 'Compact apartment surrounded by greenery.',
      fullDescription: 'Compact and functional apartment surrounded by greenery, perfect for single tenants.',
      floor: '1st',
      elevator: 'Yes',
      parkingSpace: 'No',
      available: 'Yes',
      details: {
        flat: {
          kitchenType: 'Kitchenette',
          bathroomWithToilet: 'Yes',
          balcony: 'No',
          terrace: 'No',
          market: 'Secondary',
        },
        buidling: {
          buildingType: 'Low-rise building',
          buildingMaterial: 'Brick',
          dateBuilding: '2008',
        },
        advertisement: {
          addedDate: '13-01-2025',
          lastUpdate: '23-01-2025',
          idAdvertisement: 'ADV-a9',
          views: 176,
        },
      },
    },
    {
      id: 'a10',
      imagePath: '/assets/images/apartaments/apartament10.jpg',
      name: 'ModernVista Family',
      city: 'Brodnica',
      street: 'Słoneczna 67',
      rentalFee: 2000,
      apartmentSize: 65,
      rooms: 3,
      description: 'Family-friendly apartment with plenty of space.',
      fullDescription: 'Spacious family-friendly apartment offering comfort, functionality, and safe surroundings.',
      floor: '4th',
      elevator: 'Yes',
      parkingSpace: 'Yes',
      available: 'No',
      details: {
        flat: {
          kitchenType: 'Separate kitchen',
          bathroomWithToilet: 'Yes',
          balcony: 'Yes',
          terrace: 'No',
          market: 'Primary',
        },
        buidling: {
          buildingType: 'Residential building',
          buildingMaterial: 'Concrete',
          dateBuilding: '2017',
        },
        advertisement: {
          addedDate: '14-01-2025',
          lastUpdate: '24-01-2025',
          idAdvertisement: 'ADV-a10',
          views: 389,
        },
      },
    },
    {
      id: 'a11',
      imagePath: '/assets/images/apartaments/apartament11.jpg',
      name: 'ModernVista Centrum',
      city: 'Brodnica',
      street: 'Mostowa 44',
      rentalFee: 1800,
      apartmentSize: 45,
      rooms: 2,
      description: 'Modern apartment located in the city center.',
      fullDescription: 'A modern and fully equipped apartment located in the very heart of Brodnica. Perfect for people who value proximity to city attractions, comfort, and modern design.',
      floor: '1st',
      elevator: 'Yes',
      parkingSpace: 'No',
      available: 'Yes',
      details: {
        flat: {
          kitchenType: 'Open kitchen',
          bathroomWithToilet: 'Yes',
          balcony: 'No',
          terrace: 'No',
          market: 'Primary',
        },
        buidling: {
          buildingType: 'Apartment building',
          buildingMaterial: 'Brick',
          dateBuilding: '2018',
        },
        advertisement: {
          addedDate: '01-01-2025',
          lastUpdate: '10-01-2025',
          idAdvertisement: 'ADV-a1',
          views: 245,
        },
      },
    },
    {
      id: 'a12',
      imagePath: '/assets/images/apartaments/apartament12.jpg',
      name: 'ModernVista Riverside',
      city: 'Brodnica',
      street: 'Nad Drwęcą 1',
      rentalFee: 2100,
      apartmentSize: 60,
      rooms: 3,
      description: 'Spacious apartment near the river with a calm atmosphere.',
      fullDescription: 'Spacious apartment located near the river, offering peace and beautiful surroundings. Ideal for families or people seeking relaxation close to nature.',
      floor: '3rd',
      elevator: 'Yes',
      parkingSpace: 'Yes',
      available: 'Yes',
      details: {
        flat: {
          kitchenType: 'Separate kitchen',
          bathroomWithToilet: 'Yes',
          balcony: 'Yes',
          terrace: 'No',
          market: 'Primary',
        },
        buidling: {
          buildingType: 'Residential building',
          buildingMaterial: 'Concrete',
          dateBuilding: '2016',
        },
        advertisement: {
          addedDate: '03-01-2025',
          lastUpdate: '12-01-2025',
          idAdvertisement: 'ADV-a2',
          views: 312,
        },
      },
    },
    {
      id: 'a13',
      imagePath: '/assets/images/apartaments/apartament13.jpg',
      name: 'ModernVista Park',
      city: 'Brodnica',
      street: 'Parkowa 12',
      rentalFee: 1500,
      apartmentSize: 40,
      rooms: 2,
      description: 'Cozy apartment located next to a green park.',
      fullDescription: 'A cozy and functional apartment located next to a green park. Perfect for people who appreciate calm surroundings and daily contact with nature.',
      floor: '1st',
      elevator: 'Yes',
      parkingSpace: 'No',
      available: 'Yes',
      details: {
        flat: {
          kitchenType: 'Open kitchen',
          bathroomWithToilet: 'Yes',
          balcony: 'Yes',
          terrace: 'No',
          market: 'Secondary',
        },
        buidling: {
          buildingType: 'Low-rise building',
          buildingMaterial: 'Brick',
          dateBuilding: '2012',
        },
        advertisement: {
          addedDate: '05-01-2025',
          lastUpdate: '14-01-2025',
          idAdvertisement: 'ADV-a3',
          views: 198,
        },
      },
    },
    {
      id: 'a14',
      imagePath: '/assets/images/apartaments/apartament14.jpg',
      name: 'ModernVista Lake View',
      city: 'Brodnica',
      street: 'Jeziorna 2',
      rentalFee: 2300,
      apartmentSize: 72,
      rooms: 3,
      description: 'Premium apartment with a beautiful lake view.',
      fullDescription: 'Premium apartment offering a stunning lake view and high-standard interior finish. Designed for tenants seeking luxury and comfort.',
      floor: '2nd',
      elevator: 'Yes',
      parkingSpace: 'Yes',
      available: 'No',
      details: {
        flat: {
          kitchenType: 'Open kitchen',
          bathroomWithToilet: 'Yes',
          balcony: 'Yes',
          terrace: 'Yes',
          market: 'Primary',
        },
        buidling: {
          buildingType: 'Luxury apartment building',
          buildingMaterial: 'Concrete',
          dateBuilding: '2020',
        },
        advertisement: {
          addedDate: '07-01-2025',
          lastUpdate: '15-01-2025',
          idAdvertisement: 'ADV-a4',
          views: 421,
        },
      },
    },
    {
      id: 'a15',
      imagePath: '/assets/images/apartaments/apartament15.jpg',
      name: 'ModernVista Old Town',
      city: 'Brodnica',
      street: 'Duży Rynek 53a',
      rentalFee: 1700,
      apartmentSize: 48,
      rooms: 2,
      description: 'Stylish apartment in the historic Old Town.',
      fullDescription: 'Stylish apartment located in the heart of Brodnica’s Old Town. Ideal for people who enjoy historic surroundings combined with modern comfort.',
      floor: '3rd',
      elevator: 'Yes',
      parkingSpace: 'No',
      available: 'Yes',
      details: {
        flat: {
          kitchenType: 'Open kitchen',
          bathroomWithToilet: 'Yes',
          balcony: 'No',
          terrace: 'No',
          market: 'Secondary',
        },
        buidling: {
          buildingType: 'Historic building',
          buildingMaterial: 'Brick',
          dateBuilding: '2005',
        },
        advertisement: {
          addedDate: '09-01-2025',
          lastUpdate: '18-01-2025',
          idAdvertisement: 'ADV-a5',
          views: 287,
        },
      },
    },
    {
      id: 'a16',
      imagePath: '/assets/images/apartaments/apartament16.jpg',
      name: 'ModernVista Business',
      city: 'Brodnica',
      street: 'Kamionka 22',
      rentalFee: 1900,
      apartmentSize: 55,
      rooms: 2,
      description: 'Perfect for business stays with a dedicated workspace.',
      fullDescription: 'Apartment designed for business travelers, offering a dedicated workspace and fast access to city infrastructure.',
      floor: '4th',
      elevator: 'Yes',
      parkingSpace: 'Yes',
      available: 'Yes',
      details: {
        flat: {
          kitchenType: 'Separate kitchen',
          bathroomWithToilet: 'Yes',
          balcony: 'Yes',
          terrace: 'No',
          market: 'Primary',
        },
        buidling: {
          buildingType: 'Modern apartment building',
          buildingMaterial: 'Concrete',
          dateBuilding: '2019',
        },
        advertisement: {
          addedDate: '10-01-2025',
          lastUpdate: '20-01-2025',
          idAdvertisement: 'ADV-a6',
          views: 334,
        },
      },
    },
    {
      id: 'a17',
      imagePath: '/assets/images/apartaments/apartament17.jpg',
      name: 'ModernVista Comfort',
      city: 'Brodnica',
      street: 'Wybickiego 55',
      rentalFee: 1600,
      apartmentSize: 42,
      rooms: 2,
      description: 'Comfortable apartment in a quiet residential area.',
      fullDescription: 'Comfortable apartment located in a peaceful residential area, ideal for long-term tenants seeking calm and privacy.',
      floor: '1st',
      elevator: 'Yes',
      parkingSpace: 'No',
      available: 'No',
      details: {
        flat: {
          kitchenType: 'Open kitchen',
          bathroomWithToilet: 'Yes',
          balcony: 'Yes',
          terrace: 'No',
          market: 'Secondary',
        },
        buidling: {
          buildingType: 'Residential building',
          buildingMaterial: 'Brick',
          dateBuilding: '2010',
        },
        advertisement: {
          addedDate: '11-01-2025',
          lastUpdate: '21-01-2025',
          idAdvertisement: 'ADV-a7',
          views: 198,
        },
      },
    },
    {
      id: 'a18',
      imagePath: '/assets/images/apartaments/apartament18.jpg',
      name: 'ModernVista Premium',
      city: 'Brodnica',
      street: 'Mazurska 3',
      rentalFee: 2400,
      apartmentSize: 78,
      rooms: 4,
      description: 'High-end apartment with premium interior finish.',
      fullDescription: 'High-end apartment finished with premium materials, offering spacious rooms and elegant design.',
      floor: '3rd',
      elevator: 'Yes',
      parkingSpace: 'Yes',
      available: 'Yes',
      details: {
        flat: {
          kitchenType: 'Open kitchen',
          bathroomWithToilet: 'Yes',
          balcony: 'Yes',
          terrace: 'Yes',
          market: 'Primary',
        },
        buidling: {
          buildingType: 'Luxury residence',
          buildingMaterial: 'Concrete',
          dateBuilding: '2021',
        },
        advertisement: {
          addedDate: '12-01-2025',
          lastUpdate: '22-01-2025',
          idAdvertisement: 'ADV-a8',
          views: 512,
        },
      },
    },
    {
      id: 'a19',
      imagePath: '/assets/images/apartaments/apartament19.jpg',
      name: 'ModernVista Green',
      city: 'Brodnica',
      street: 'Zielona 8',
      rentalFee: 1450,
      apartmentSize: 38,
      rooms: 1,
      description: 'Compact apartment surrounded by greenery.',
      fullDescription: 'Compact and functional apartment surrounded by greenery, perfect for single tenants.',
      floor: '1st',
      elevator: 'Yes',
      parkingSpace: 'No',
      available: 'Yes',
      details: {
        flat: {
          kitchenType: 'Kitchenette',
          bathroomWithToilet: 'Yes',
          balcony: 'No',
          terrace: 'No',
          market: 'Secondary',
        },
        buidling: {
          buildingType: 'Low-rise building',
          buildingMaterial: 'Brick',
          dateBuilding: '2008',
        },
        advertisement: {
          addedDate: '13-01-2025',
          lastUpdate: '23-01-2025',
          idAdvertisement: 'ADV-a9',
          views: 176,
        },
      },
    },
    {
      id: 'a20',
      imagePath: '/assets/images/apartaments/apartament20.jpg',
      name: 'ModernVista Family',
      city: 'Brodnica',
      street: 'Słoneczna 67',
      rentalFee: 2000,
      apartmentSize: 65,
      rooms: 3,
      description: 'Family-friendly apartment with plenty of space.',
      fullDescription: 'Spacious family-friendly apartment offering comfort, functionality, and safe surroundings.',
      floor: '4th',
      elevator: 'Yes',
      parkingSpace: 'Yes',
      available: 'No',
      details: {
        flat: {
          kitchenType: 'Separate kitchen',
          bathroomWithToilet: 'Yes',
          balcony: 'Yes',
          terrace: 'No',
          market: 'Primary',
        },
        buidling: {
          buildingType: 'Residential building',
          buildingMaterial: 'Concrete',
          dateBuilding: '2017',
        },
        advertisement: {
          addedDate: '14-01-2025',
          lastUpdate: '24-01-2025',
          idAdvertisement: 'ADV-a10',
          views: 389,
        },
      },
    },
]);


  getAllApartaments(): ApartamentsModel[] {
    return this.Apartaments();
  }
  getApartamentById(id: string | undefined): ApartamentsModel | undefined {
    return this.Apartaments().find((apartament) => apartament.id === id);
  }

}
