import { Injectable, signal } from '@angular/core';
import { ApartamentsModel } from './apartaments.model';

@Injectable({
  providedIn: 'root',
})
export class ApartamentsStorage {
  public Apartaments = signal<ApartamentsModel[]>([
    {
      id: 'a1',
      name: 'ModernVista Centrum',
      city: 'Brodnica',
      street: 'Mostowa 44',
      rentalFee: 1800,
      apartmentSize: 45,
      rooms: 2,
      description: 'Modern apartment located in the city center.',
      parkingSpace: 'No',
      available: 'Yes',
      imagePath: '/assets/images/apartaments/apartament1.jpg',
      floor: "1st",
      elevator: 'Yes',
    },
    {
      id: 'a2',
      name: 'ModernVista Riverside',
      city: 'Brodnica',
      street: 'Nad Drwęcą 1',
      rentalFee: 2100,
      apartmentSize: 60,
      rooms: 3,
      description: 'Spacious apartment near the river with a calm atmosphere.',
      parkingSpace: 'Yes',
      available: 'Yes',
      imagePath: 'assets/images/apartaments/apartament2.jpg',
      floor: "1st",
      elevator: 'Yes',
    },
    {
      id: 'a3',
      name: 'ModernVista Park',
      city: 'Brodnica',
      street: 'Parkowa 12',
      rentalFee: 1500,
      apartmentSize: 40,
      rooms: 2,
      description: 'Cozy apartment located next to a green park.',
      parkingSpace: 'No',
      available: 'Yes',
      imagePath: 'assets/images/apartaments/apartament3.jpg',
      floor: "1st",
      elevator: 'Yes',
    },
    {
      id: 'a4',
      name: 'ModernVista Lake View',
      city: 'Brodnica',
      street: 'Jeziorna 2',
      rentalFee: 2300,
      apartmentSize: 72,
      rooms: 3,
      description: 'Premium apartment with a beautiful lake view.',
      parkingSpace: 'Yes',
      available: 'No',
      imagePath: 'assets/images/apartaments/apartament4.jpg',
      floor: "1st",
      elevator: 'Yes',
    },
    {
      id: 'a5',
      name: 'ModernVista Old Town',
      city: 'Brodnica',
      street: 'Duży Rynek 53a',
      rentalFee: 1700,
      apartmentSize: 48,
      rooms: 2,
      description: 'Stylish apartment in the historic Old Town.',
      parkingSpace: 'No',
      available: 'Yes',
      imagePath: 'assets/images/apartaments/apartament5.jpg',
      floor: "1st",
      elevator: 'Yes',
    },
    {
      id: 'a6',
      name: 'ModernVista Business',
      city: 'Brodnica',
      street: 'Kamionka 22',
      rentalFee: 1900,
      apartmentSize: 55,
      rooms: 2,
      description: 'Perfect for business stays with a dedicated workspace.',
      parkingSpace: 'Yes',
      available: 'Yes',
      imagePath: 'assets/images/apartaments/apartament6.jpg',
      floor: "1st",
      elevator: 'Yes',
    },
    {
      id: 'a7',
      name: 'ModernVista Comfort',
      city: 'Brodnica',
      street: 'Wybickiego 55',
      rentalFee: 1600,
      apartmentSize: 42,
      rooms: 2,
      description: 'Comfortable apartment in a quiet residential area.',
      parkingSpace: 'No',
      available: 'No',
      imagePath: 'assets/images/apartaments/apartament7.jpg',
      floor: "1st",
      elevator: 'Yes',
    },
    {
      id: 'a8',
      name: 'ModernVista Premium',
      city: 'Brodnica',
      street: 'Mazurska 3',
      rentalFee: 2400,
      apartmentSize: 78,
      rooms: 4,
      description: 'High-end apartment with premium interior finish.',
      parkingSpace: 'Yes',
      available: 'Yes',
      imagePath: 'assets/images/apartaments/apartament8.jpg',
      floor: "1st",
      elevator: 'Yes',
    },
    {
      id: 'a9',
      name: 'ModernVista Green',
      city: 'Brodnica',
      street: 'Zielona 8',
      rentalFee: 1450,
      apartmentSize: 38,
      rooms: 1,
      description: 'Compact apartment surrounded by greenery.',
      parkingSpace: 'No',
      available: 'Yes',
      imagePath: 'assets/images/apartaments/apartament9.jpg',
      floor: "1st",
      elevator: 'Yes',
    },
    {
      id: 'a10',
      name: 'ModernVista Family',
      city: 'Brodnica',
      street: 'Słoneczna 67',
      rentalFee: 2000,
      apartmentSize: 65,
      rooms: 3,
      description: 'Family-friendly apartment with plenty of space.',
      parkingSpace: 'Yes',
      available: 'No',
      imagePath: 'assets/images/apartaments/apartament10.jpg',
      floor: "1st",
      elevator: 'Yes',
    },
    {
      id: 'a11',
      name: 'ModernVista Loft',
      city: 'Brodnica',
      street: 'Fabryczna 23',
      rentalFee: 1850,
      apartmentSize: 50,
      rooms: 2,
      description: 'Loft-style apartment with open-plan layout.',
      parkingSpace: 'No',
      available: 'Yes',
      imagePath: 'assets/images/apartaments/apartament11.jpg',
      floor: "1st",
      elevator: 'Yes',
    },
    {
      id: 'a12',
      name: 'ModernVista Harmony',
      city: 'Brodnica',
      street: 'Spokojna 44',
      rentalFee: 1650,
      apartmentSize: 46,
      rooms: 2,
      description: 'Peaceful apartment ideal for long-term stays.',
      parkingSpace: 'Yes',
      available: 'Yes',
      imagePath: 'assets/images/apartaments/apartament12.jpg',
      floor: "1st",
      elevator: 'Yes',
    },
    {
      id: 'a13',
      name: 'ModernVista Urban',
      city: 'Brodnica',
      street: 'Kościuszki 64',
      rentalFee: 1750,
      apartmentSize: 49,
      rooms: 2,
      description: 'Modern urban apartment close to city amenities.',
      parkingSpace: 'No',
      available: 'Yes',
      imagePath: 'assets/images/apartaments/apartament13.jpg',
      floor: "1st",
      elevator: 'Yes',
    },
    {
      id: 'a14',
      name: 'ModernVista Panorama',
      city: 'Brodnica',
      street: 'Widokowa 15',
      rentalFee: 2200,
      apartmentSize: 70,
      rooms: 3,
      description: 'Apartment with panoramic views of the city.',
      parkingSpace: 'Yes',
      available: 'No',
      imagePath: 'assets/images/apartaments/apartament14.jpg',
      floor: "1st",
      elevator: 'Yes',
    },
    {
      id: 'a15',
      name: 'ModernVista Studio',
      city: 'Brodnica',
      street: 'Krótka 3',
      rentalFee: 1300,
      apartmentSize: 30,
      rooms: 1,
      description: 'Small studio apartment ideal for single tenants.',
      parkingSpace: 'No',
      available: 'Yes',
      imagePath: 'assets/images/apartaments/apartament15.jpg',
      floor: "1st",
      elevator: 'Yes',
    },
    {
      id: 'a16',
      name: 'ModernVista Residence',
      city: 'Brodnica',
      street: 'Polna 5',
      rentalFee: 1950,
      apartmentSize: 58,
      rooms: 3,
      description: 'Well-balanced apartment combining comfort and space.',
      parkingSpace: 'Yes',
      available: 'Yes',
      imagePath: 'assets/images/apartaments/apartament16.jpg',
      floor: "1st",
      elevator: 'Yes',
    },
    {
      id: 'a17',
      name: 'ModernVista Elite',
      city: 'Brodnica',
      street: 'Lipowa 13',
      rentalFee: 2500,
      apartmentSize: 80,
      rooms: 4,
      description: 'Elite apartment with top-quality materials.',
      parkingSpace: 'Yes',
      available: 'No',
      imagePath: 'assets/images/apartaments/apartament17.jpg',
      floor: "1st",
      elevator: 'Yes',
    },
    {
      id: 'a18',
      name: 'ModernVista Corner',
      city: 'Brodnica',
      street: 'Dworcowa 33',
      rentalFee: 1600,
      apartmentSize: 44,
      rooms: 2,
      description: 'Bright corner apartment close to transport links.',
      parkingSpace: 'No',
      available: 'Yes',
      imagePath: 'assets/images/apartaments/apartament18.jpg',
      floor: "1st",
      elevator: 'Yes',
    },
    {
      id: 'a19',
      name: 'ModernVista Nature',
      city: 'Brodnica',
      street: 'Leśna 1',
      rentalFee: 1700,
      apartmentSize: 47,
      rooms: 2,
      description: 'Apartment close to forest and walking trails.',
      parkingSpace: 'Yes',
      available: 'Yes',
      imagePath: 'assets/images/apartaments/apartament19.jpg',
      floor: "1st",
      elevator: 'Yes',
    },
    {
      id: 'a20',
      name: 'ModernVista Signature',
      city: 'Brodnica',
      street: 'Mickiewicza 44',
      rentalFee: 2250,
      apartmentSize: 73,
      rooms: 3,
      description: 'Signature apartment offering high comfort and style.',
      parkingSpace: 'Yes',
      available: 'Yes',
      imagePath: 'assets/images/apartaments/apartament20.jpg',
      floor: "1st",
      elevator: 'Yes',
    },
  ])

  getAllApartaments(): ApartamentsModel[] {
    return this.Apartaments();
  }
}
