export interface ApartamentsModel {
    id: string,
    imagePath: string,
    name: string,
    city: string,
    street: string,
    rentalFee: number,
    apartmentSize: number,
    rooms: number,
    description: string,
    floor: string,
    elevator: 'Yes' | 'No',
    parkingSpace: 'Yes' | 'No',
    available: 'Yes' | 'No',
    fullDescription: string,

    kitchenType: string | null,
    bathroomWithToilet: 'Yes' | 'No' | null,
    balcony: 'Yes' | 'No' | null,
    terrace: 'Yes' | 'No' | null,
    market: 'Secondary' | 'Primary' | null,

    buildingType: string | null,
    buildingMaterial: string | null,
    dateBuilding: string | null,

    addedDate: string | null,
    lastUpdate: string | null,
    idAdvertisement: string | null,
    views: number | null,
}