import { Injectable, signal } from '@angular/core';
import { opinionsModel } from './opinions.model';

@Injectable({
  providedIn: 'root',
})
export class OpinionsStorage {
  protected opinions = signal<opinionsModel[]>([
    {
      CustomerId: 'c1',
      gender: 'female',
      firstName: 'Emily',
      lastName: 'Carter',
      opinionDate: '05-01-2025',
      opinionContent: 'Very clean apartment with a modern and cozy interior. The location was perfect, close to shops and restaurants. Everything inside was well prepared and exactly as described. The check-in process was smooth and hassle-free. I would definitely recommend this place to anyone visiting the city.',
      apartamentId: 'a1',
      rating: 5,
    },
    {
      CustomerId: 'c2',
      gender: 'male',
      firstName: 'James',
      lastName: 'Walker',
      opinionDate: '08-01-2025',
      opinionContent: 'The apartment was comfortable and well equipped for a short stay. I appreciated the quiet neighborhood and good sound insulation. All amenities were working properly and the space was very clean. Communication with the host was fast and helpful. Overall, a very pleasant experience.',
      apartamentId: 'a2',
      rating: 4,
    },
    {
      CustomerId: 'c3',
      gender: 'female',
      firstName: 'Olivia',
      lastName: 'Brown',
      opinionDate: '12-01-2025',
      opinionContent: 'A beautifully designed apartment with a modern interior style. The neighborhood was calm and perfect for relaxing after a long day. The apartment had everything needed for daily use. Cleanliness was at a very high level. I would gladly stay here again.',
      apartamentId: 'a3',
      rating: 5,
    },
    {
      CustomerId: 'c4',
      gender: 'male',
      firstName: 'Daniel',
      lastName: 'Evans',
      opinionDate: '15-01-2025',
      opinionContent: 'The apartment offered great value for the price. It was clean, functional and well located. The rooms were spacious and comfortable. Everything matched the description provided online. A solid choice for both short and longer stays.',
      apartamentId: 'a4',
      rating: 4,
    },
    {
      CustomerId: 'c5',
      gender: 'female',
      firstName: 'Sophia',
      lastName: 'Miller',
      opinionDate: '18-01-2025',
      opinionContent: 'Excellent location close to the city center and public transport. The apartment was bright, clean and very well maintained. Check-in was quick and simple. The interior felt welcoming and comfortable. I truly enjoyed my stay here.',
      apartamentId: 'a5',
      rating: 5,
    },
    {
      CustomerId: 'c6',
      gender: 'male',
      firstName: 'Michael',
      lastName: 'Turner',
      opinionDate: '21-01-2025',
      opinionContent: 'A spacious apartment that was perfect for a longer stay. The kitchen was fully equipped and easy to use. Everything was clean and well organized. The area was quiet and peaceful. I felt at home during my entire stay.',
      apartamentId: 'a6',
      rating: 5,
    },
    {
      CustomerId: 'c7',
      gender: 'female',
      firstName: 'Isabella',
      lastName: 'Wilson',
      opinionDate: '24-01-2025',
      opinionContent: 'Cozy apartment with a warm and welcoming atmosphere. All basic amenities were available and in good condition. The place was clean and well prepared before arrival. The neighborhood felt safe and calm. Overall, a very comfortable stay.',
      apartamentId: 'a7',
      rating: 4,
    },
    {
      CustomerId: 'c8',
      gender: 'male',
      firstName: 'Liam',
      lastName: 'Anderson',
      opinionDate: '27-01-2025',
      opinionContent: 'The apartment exceeded my expectations in every way. Modern design, great layout and excellent cleanliness. The location was convenient and easy to access. Communication with the owner was smooth. Highly recommended.',
      apartamentId: 'a8',
      rating: 5,
    },
    {
      CustomerId: 'c9',
      gender: 'female',
      firstName: 'Charlotte',
      lastName: 'Taylor',
      opinionDate: '30-01-2025',
      opinionContent: 'Very comfortable apartment with stylish interior design. The space was bright and well arranged. Everything was clean and ready upon arrival. The location made it easy to explore the city. I would happily book this apartment again.',
      apartamentId: 'a9',
      rating: 5,
    },
    {
      CustomerId: 'c10',
      gender: 'male',
      firstName: 'Benjamin',
      lastName: 'Harris',
      opinionDate: '02-02-2025',
      opinionContent: 'A solid and well-located apartment close to key attractions. The rooms were clean and nicely furnished. All basic needs were covered. The stay was smooth from start to finish. Good choice for business or leisure trips.',
      apartamentId: 'a10',
      rating: 4,
    },
    {
      CustomerId: 'c11',
      gender: 'female',
      firstName: 'Amelia',
      lastName: 'Clark',
      opinionDate: '05-02-2025',
      opinionContent: 'Everything was perfectly prepared before arrival. The apartment was spotless and smelled fresh. Furniture and equipment were modern and well maintained. The stay was very comfortable from start to finish. I would definitely recommend this place to others.',
      apartamentId: 'a11',
      rating: 5,
    },
    {
      CustomerId: 'c12',
      gender: 'male',
      firstName: 'Ethan',
      lastName: 'Lewis',
      opinionDate: '08-02-2025',
      opinionContent: 'The apartment was located in a quiet and peaceful area. It offered everything needed for a comfortable stay. The interior was clean and well organized. I appreciated the calm atmosphere after a busy day. Overall, a very good experience.',
      apartamentId: 'a12',
      rating: 4,
    },
    {
      CustomerId: 'c13',
      gender: 'female',
      firstName: 'Mia',
      lastName: 'Hall',
      opinionDate: '11-02-2025',
      opinionContent: 'This apartment was perfect for a weekend getaway. The space was cozy, clean and nicely arranged. Everything was easy to use and well explained. The location was convenient and accessible. I would gladly return in the future.',
      apartamentId: 'a13',
      rating: 5,
    },
    {
      CustomerId: 'c14',
      gender: 'male',
      firstName: 'Alexander',
      lastName: 'Young',
      opinionDate: '14-02-2025',
      opinionContent: 'High-quality apartment with a modern and elegant interior. Everything was spotless and well prepared. The check-in process was smooth and professional. The overall standard exceeded my expectations. I highly recommend this apartment.',
      apartamentId: 'a14',
      rating: 5,
    },
    {
      CustomerId: 'c15',
      gender: 'female',
      firstName: 'Ella',
      lastName: 'King',
      opinionDate: '17-02-2025',
      opinionContent: 'A very comfortable apartment that truly felt like home. The rooms were warm, clean and inviting. All amenities worked perfectly. The stay was calm and relaxing. I really enjoyed my time here.',
      apartamentId: 'a15',
      rating: 4,
    },
    {
      CustomerId: 'c16',
      gender: 'male',
      firstName: 'Noah',
      lastName: 'Wright',
      opinionDate: '20-02-2025',
      opinionContent: 'Modern apartment with great attention to detail. The interior was stylish and very clean. The location was excellent and easy to reach. Everything was prepared exactly as promised. A great choice for a comfortable stay.',
      apartamentId: 'a16',
      rating: 5,
    },
    {
      CustomerId: 'c17',
      gender: 'female',
      firstName: 'Grace',
      lastName: 'Lopez',
      opinionDate: '23-02-2025',
      opinionContent: 'An excellent experience from beginning to end. The apartment was clean, bright and well organized. The neighborhood was quiet and pleasant. Communication was easy and helpful. I would definitely stay here again.',
      apartamentId: 'a17',
      rating: 5,
    },
    {
      CustomerId: 'c18',
      gender: 'male',
      firstName: 'Lucas',
      lastName: 'Martinez',
      opinionDate: '26-02-2025',
      opinionContent: 'Very nice apartment equipped with everything needed. The space was clean and comfortable. The interior design was modern and practical. The stay was smooth and problem-free. A very good option for travelers.',
      apartamentId: 'a18',
      rating: 4,
    },
    {
      CustomerId: 'c19',
      gender: 'female',
      firstName: 'Lily',
      lastName: 'Robinson',
      opinionDate: '01-03-2025',
      opinionContent: 'Clean, bright and welcoming apartment. The rooms were spacious and nicely furnished. Everything was ready upon arrival. The location made it easy to get around. I was very satisfied with my stay.',
      apartamentId: 'a19',
      rating: 5,
    },
    {
      CustomerId: 'c20',
      gender: 'male',
      firstName: 'Henry',
      lastName: 'Scott',
      opinionDate: '04-03-2025',
      opinionContent: 'Excellent apartment with high-quality finish. Everything was clean, modern and well maintained. Communication was quick and professional. The stay was comfortable and stress-free. I would highly recommend this place.',
      apartamentId: 'a20',
      rating: 5,
    },
  ]);

  getAllOpinions() {
    return this.opinions();
  }

  getOpinionById(id:string | undefined): opinionsModel | undefined {
    return this.opinions().find((opinion) => opinion.CustomerId === id);
  }
}
