import { Injectable, signal } from '@angular/core';
import { opinionsModel } from './opinions.model';

@Injectable({
  providedIn: 'root',
})
export class OpinionsStorage {
  protected opinions = signal<opinionsModel[]>([
    {
      CustomerId: 'c1',
      gender: 'female',
      firstName: 'Emily',
      lastName: 'Carter',
      opinionDate: '05-01-2025',
      opinionContent: 'Very clean apartment and great location.',
      apartamentId: 'a1',
      rating: 5,
    },
    {
      CustomerId: 'c2',
      gender: 'male',
      firstName: 'James',
      lastName: 'Walker',
      opinionDate: '08-01-2025',
      opinionContent: 'Comfortable stay, everything worked perfectly.',
      apartamentId: 'a2',
      rating: 4,
    },
    {
      CustomerId: 'c3',
      gender: 'female',
      firstName: 'Olivia',
      lastName: 'Brown',
      opinionDate: '12-01-2025',
      opinionContent: 'Modern interior and very quiet neighborhood.',
      apartamentId: 'a3',
      rating: 5,
    },
    {
      CustomerId: 'c4',
      gender: 'male',
      firstName: 'Daniel',
      lastName: 'Evans',
      opinionDate: '15-01-2025',
      opinionContent: 'Nice apartment, good value for the price.',
      apartamentId: 'a4',
      rating: 4,
    },
    {
      CustomerId: 'c5',
      gender: 'female',
      firstName: 'Sophia',
      lastName: 'Miller',
      opinionDate: '18-01-2025',
      opinionContent: 'Great location and very smooth check-in process.',
      apartamentId: 'a5',
      rating: 5,
    },
    {
      CustomerId: 'c6',
      gender: 'male',
      firstName: 'Michael',
      lastName: 'Turner',
      opinionDate: '21-01-2025',
      opinionContent: 'Spacious apartment, perfect for a longer stay.',
      apartamentId: 'a6',
      rating: 5,
    },
    {
      CustomerId: 'c7',
      gender: 'female',
      firstName: 'Isabella',
      lastName: 'Wilson',
      opinionDate: '24-01-2025',
      opinionContent: 'Clean, cozy and very well equipped.',
      apartamentId: 'a7',
      rating: 4,
    },
    {
      CustomerId: 'c8',
      gender: 'male',
      firstName: 'Liam',
      lastName: 'Anderson',
      opinionDate: '27-01-2025',
      opinionContent: 'Excellent apartment, highly recommended.',
      apartamentId: 'a8',
      rating: 5,
    },
    {
      CustomerId: 'c9',
      gender: 'female',
      firstName: 'Charlotte',
      lastName: 'Taylor',
      opinionDate: '30-01-2025',
      opinionContent: 'Very comfortable and nicely designed.',
      apartamentId: 'a9',
      rating: 5,
    },
    {
      CustomerId: 'c10',
      gender: 'male',
      firstName: 'Benjamin',
      lastName: 'Harris',
      opinionDate: '02-02-2025',
      opinionContent: 'Good apartment in a convenient location.',
      apartamentId: 'a10',
      rating: 4,
    },
    {
      CustomerId: 'c11',
      gender: 'female',
      firstName: 'Amelia',
      lastName: 'Clark',
      opinionDate: '05-02-2025',
      opinionContent: 'Everything was clean and well prepared.',
      apartamentId: 'a11',
      rating: 5,
    },
    {
      CustomerId: 'c12',
      gender: 'male',
      firstName: 'Ethan',
      lastName: 'Lewis',
      opinionDate: '08-02-2025',
      opinionContent: 'Nice place, quiet and comfortable.',
      apartamentId: 'a12',
      rating: 4,
    },
    {
      CustomerId: 'c13',
      gender: 'female',
      firstName: 'Mia',
      lastName: 'Hall',
      opinionDate: '11-02-2025',
      opinionContent: 'Perfect apartment for a weekend stay.',
      apartamentId: 'a13',
      rating: 5,
    },
    {
      CustomerId: 'c14',
      gender: 'male',
      firstName: 'Alexander',
      lastName: 'Young',
      opinionDate: '14-02-2025',
      opinionContent: 'High standard and very good service.',
      apartamentId: 'a14',
      rating: 5,
    },
    {
      CustomerId: 'c15',
      gender: 'female',
      firstName: 'Ella',
      lastName: 'King',
      opinionDate: '17-02-2025',
      opinionContent: 'Comfortable apartment, felt like home.',
      apartamentId: 'a15',
      rating: 4,
    },
    {
      CustomerId: 'c16',
      gender: 'male',
      firstName: 'Noah',
      lastName: 'Wright',
      opinionDate: '20-02-2025',
      opinionContent: 'Modern, clean and very well located.',
      apartamentId: 'a16',
      rating: 5,
    },
    {
      CustomerId: 'c17',
      gender: 'female',
      firstName: 'Grace',
      lastName: 'Lopez',
      opinionDate: '23-02-2025',
      opinionContent: 'Great experience, I would stay again.',
      apartamentId: 'a17',
      rating: 5,
    },
    {
      CustomerId: 'c18',
      gender: 'male',
      firstName: 'Lucas',
      lastName: 'Martinez',
      opinionDate: '26-02-2025',
      opinionContent: 'Very nice apartment with all amenities.',
      apartamentId: 'a18',
      rating: 4,
    },
    {
      CustomerId: 'c19',
      gender: 'female',
      firstName: 'Lily',
      lastName: 'Robinson',
      opinionDate: '01-03-2025',
      opinionContent: 'Clean, bright and comfortable place.',
      apartamentId: 'a19',
      rating: 5,
    },
    {
      CustomerId: 'c20',
      gender: 'male',
      firstName: 'Henry',
      lastName: 'Scott',
      opinionDate: '04-03-2025',
      opinionContent: 'Excellent quality and very good communication.',
      apartamentId: 'a20',
      rating: 5,
    },
  ]);

  getAllOpinions() {
    return this.opinions();
  }

  // getOpinionById(id:string): opinionsModel | undefined {
  //   return this.opinions.find((opinion) => opinion.CustomerId === id);
  // }
}
